language: java
dist: bionic
jdk:
  - oraclejdk11
before_install:
  - chmod +x maybe-release.sh
install:
    - mvn install -Dmaven.javadoc.skip=true -B -V
before_script:
  - git config --global user.email "swisspush@post.ch"
  - git config --global user.name "Travis-CI"
  # install groovy
  - TERM=dumb groovy --version
  - export GROOVY_VERSION=3.0.0-alpha-2
  - wget http://dl.bintray.com/groovy/maven/apache-groovy-binary-$GROOVY_VERSION.zip -O /tmp/groovy.zip
  - unzip /tmp/groovy.zip -d $PWD/.groovy
  - export PATH=$PWD/.groovy/groovy-$GROOVY_VERSION/bin:$PATH
  - echo "groovy installed ${GROOVY_VERSION}"
script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - ./maybe-release.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
